[package]
name = "cybernetics"
version = "0.1.1"
authors = ["hbdgr <hbdgr@protonmail.com>"]

[dependencies]
sodiumoxide = "0.0.16"
ws = "0.7.6"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

bincode = "1.0.1"
